### Get request to read all users
GET http://localhost:3000/api/v2/users

###Post request to create a new user
POST  http://localhost:3000/api/v2/users
Content-Type: application/json

{
    "username":"ai3",
    "email":"ai3@email.com",
    "password":"12345678",
    "role": "admin"
}

###Delete
DELETE http://localhost:3000/api/v2/users/5


###post login user
POST http://localhost:3000/api/v2/users/auth/cookie/login
Content-Type: application/json

{
    "email": "ai3@email.com",
    "password": "12345678"
}


###post logout a user
POST http://localhost:3000/api/v2/users/auth/cookie/logout


###get check user auth
Get http://localhost:3000/api/v2/users/auth/cookie/me

### ask ai
POST http://localhost:3000/api/v2/users/auth/ai/ask
Content-Type: application/json

{
    "question": "who are user?",
    "topK": 5
}