### Get request to read all users
GET http://localhost:3000/api/v1/users

###Post request to create a new user
POST  http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "name":"Bob",
    "email":"Bob@example.com"
}

###Delete
DELETE http://localhost:3000/api/v1/users/2
